# Generated by Django 4.1.2 on 2022-12-02 21:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categorys',
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
                ('color', models.CharField(max_length=255)),
                ('alias_color', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('qtd', models.DecimalField(decimal_places=2, max_digits=2)),
                ('type', models.CharField(max_length=99)),
                ('size', models.DecimalField(decimal_places=2, max_digits=2)),
                ('uri_image', models.CharField(max_length=1000)),
                ('price', models.FloatField()),
                ('top_products', models.BooleanField(default=True)),
                ('discount', models.DecimalField(decimal_places=2, max_digits=2)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categorys', to='products.category')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
    ]
